
name: Push-Image
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - master
    paths:
      - .github/workflows/ 
      - docker/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/build_image.yml
      - docker/**

jobs:
  push-image:
    name: Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build Image
        run: docker/build.sh
