name: Start Railway Service in the Morning

on:
  schedule:
    # Start at 8 AM UTC Monday to Friday
    - cron: '0 8 * * mon-fri'  # Monday to Friday, 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  start-service:
    runs-on: ubuntu-latest
    steps:
      - name: Scale up service frontend (replicas = 1)
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -d '{"query":"mutation { serviceScale(id: \"${{ secrets.RAILWAY_SERVICE_ID_FRONTEND }}\", input: { replicas: 1 }) { id } }"}'
      - name: Scale up service backend (replicas = 1)
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -d '{"query":"mutation { serviceScale(id: \"${{ secrets.RAILWAY_SERVICE_ID_BACKEND }}\", input: { replicas: 1 }) { id } }"}'

