name: Stop Railway Service at Night

on:
  schedule:
    # Stop at 4 PM UTC every weekday (Monday to Friday)
    - cron: '0 16 * * mon-fri'  # Every Monday to Friday at 4 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  stop-service:
    runs-on: ubuntu-latest
    steps:
      - name: Scale down service frontend (replicas = 0)
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -d '{"query":"mutation { serviceScale(id: \"${{ secrets.RAILWAY_SERVICE_ID_FRONTEND }}\", input: { replicas: 0 }) { id } }"}'
      - name: Scale down service backend (replicas = 0)
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -d '{"query":"mutation { serviceScale(id: \"${{ secrets.RAILWAY_SERVICE_ID_BACKEND }}\", input: { replicas: 0 }) { id } }"}'

      - name: Scale down service db (replicas = 0)
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -d '{"query":"mutation { serviceScale(id: \"${{ secrets.RAILWAY_SERVICE_ID_DB }}\", input: { replicas: 0 }) { id } }"}'

