name: Eval script

on:
  pull_request_target:
    branches: [ master ]

jobs:
  eval:
    runs-on: [self-hosted, linux]

    steps:
    - name: Test Self-Hosted
      run: echo "hello and test self hosted"
